runtime: python37

handlers:
- url: /
  static_files: frontend/app.html
  upload: frontend/app.html
  secure: always
  redirect_http_response_code: 301

- url: /(script.js|style.css|kicksmarter.png)
  static_files: frontend/\1
  upload: frontend/(script.js|style.css|kicksmarter.png)
  secure: always
  redirect_http_response_code: 301

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301